# .travis.yaml
language: generic
os: linux
dist: xenial
before_install:
    - pyenv versions
    - pyenv shell 3.7.1
    - pip3 install --upgrade pip
after_success:
    - pwd
before_deploy:
    # install PyGithub
    - pip3 install PyGithub
    # download githubrelease.py
    - ls -al
    - cd ..
    - wget https://raw.githubusercontent.com/Immueggpain/citools/master/githubrelease.py
    - ls
    - zip eat_bag-$TRAVIS_TAG.zip eat_bag/*
deploy:
    provider: script
    script: python3 githubrelease.py "eat_bag-$TRAVIS_TAG.zip"
    cleanup: false
    skip_cleanup: true
    on:
        tags: true
